# Build settings
markdown: kramdown
theme: minima

title: "Professional Works"
author: "Casey Brito"
description: >
  "An assortment of my professional works such as teachings and technical write-ups."
github_username: cabrito
rss: rss

show_excerpts: false

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - teachings.md
 
minima:
date_format: "%b %-d, %Y"
